# FROM eclipse-temurin:21-jdk AS build
# WORKDIR /app
# COPY . .
# RUN ./mvnw clean package -DskipTests

# FROM eclipse-temurin:21-jdk
# WORKDIR /app
# COPY --from=build /app/target/*.jar app.jar
# ENTRYPOINT ["java", "-jar", "app.jar"]

FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copy pom first and download dependencies
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
RUN ./mvnw dependency:go-offline

# Now copy the actual source
COPY src src

CMD ["./mvnw", "spring-boot:run"]